const Keys = [
  {
    name: "7",
    value: "7",
    type: "number",
    onClick: "handleClick",
    className: "",
  },
  {
    name: "8",
    value: "8",
    type: "number",
    onClick: "handleClick",
    className: "",
  },
  {
    name: "9",
    value: "9",
    type: "number",
    onClick: "handleClick",
    className: "",
  },
  {
    name: "DEL",
    value: "DEL",
    type: "delete",
    onClick: "delete",
    className: "del-reset",
  },
  {
    name: "4",
    value: "4",
    type: "number",
    onClick: "handleClick",
    className: "",
  },
  {
    name: "5",
    value: "5",
    type: "number",
    onClick: "handleClick",
    className: "",
  },
  {
    name: "6",
    value: "6",
    type: "number",
    onClick: "handleClick",
    className: "",
  },
  {
    name: "+",
    value: "+",
    type: "operator",
    onClick: "handleClick",
    className: "",
  },
  {
    name: "1",
    value: "1",
    type: "number",
    onClick: "handleClick",
    className: "",
  },
  {
    name: "2",
    value: "2",
    type: "number",
    onClick: "handleClick",
    className: "",
  },
  {
    name: "3",
    value: "3",
    type: "number",
    onClick: "handleClick",
    className: "",
  },
  {
    name: "-",
    value: "-",
    type: "operator",
    onClick: "handleClick",
    className: "",
  },
  {
    name: ".",
    value: ".",
    type: "number",
    onClick: "handleClick",
    className: "",
  },
  {
    name: "0",
    value: "0",
    type: "number",
    onClick: "handleClick",
    className: "",
  },
  {
    name: "/",
    value: "/",
    type: "operator",
    onClick: "handleClick",
    className: "",
  },
  {
    name: "x",
    value: "*",
    type: "operator",
    onClick: "handleClick",
    className: "",
  },
  {
    name: "RESET",
    value: "RESET",
    type: "reset",
    onClick: "reset",
    className: "span-two del-reset",
  },
  {
    name: "=",
    value: "=",
    type: "equals",
    onClick: "calculate",
    className: "span-two equals",
  },
];

export default Keys;
